<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="dependent.aspx.cs" Inherits="Default2" %>



<%@ Register assembly="RJS.Web.WebControl.PopCalendar.Net.2010" namespace="RJS.Web.WebControl" tagprefix="rjs" %>




<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            text-align: center;
        }
        .Gridview1
        {}
        .style3
        {
            text-align: left;
        }
        .style4
        {
            text-align: left;
            height: 18px;
        }
        .style5
        {
        }
        .style6
        {
            text-align: left;
            height: 29px;
        }
        .style7
        {
            height: 29px;
        }
        .style8
        {
            width: 177px;
        }
        .style9
        {
            height: 29px;
            width: 177px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <table class="style1" "boder:1px">
        <tr>
            <td>
                <asp:DetailsView ID="DetailsView1" runat="server" 
                    DataKeyNames="empno" DataSourceID="AccessDataSource3" Height="50px" 
                    Width="125px" AutoGenerateEditButton="True" DefaultMode="Edit"  
                    
                    AutoGenerateRows="False">
                    <Fields>
                        <asp:BoundField DataField="empno" HeaderText="empno" ReadOnly="True" 
                            SortExpression="empno" />
                        <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                        <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                        <asp:BoundField DataField="Last_grade" HeaderText="Last_grade" 
                            SortExpression="Last_grade" />
                        <asp:BoundField DataField="Last_designation" HeaderText="Last_designation" 
                            SortExpression="Last_designation" />
                        <asp:BoundField DataField="Last_Unit" HeaderText="Last_Unit" 
                            SortExpression="Last_Unit" />
                        <asp:BoundField DataField="Last_Location" HeaderText="Last_Location" 
                            SortExpression="Last_Location" />
                        <asp:BoundField DataField="Parent_Division" HeaderText="Parent_Division" 
                            SortExpression="Parent_Division" />
                    </Fields>
                </asp:DetailsView>
                <asp:AccessDataSource ID="AccessDataSource3" runat="server" 
                    DataFile="~/App_Data/Exgratia.accdb" 
                    SelectCommand="SELECT * FROM [Emp_master] WHERE ([empno] = ?)" UpdateCommand="UPDATE [Emp_master] SET [Name]=@name,[DOB]=@dob,[Last_grade]=@l_grade,[Last_designation]=@l_designation,[Last_Unit]=@l_unit,[Last_location]=@l_location,[Parent_Division]=@p_division WHERE [empno]=@empno" >
                    <SelectParameters>
                        <asp:SessionParameter   SessionField="user" Name="empno" Type="String" />
                    </SelectParameters>
                </asp:AccessDataSource>
                <br />
            </td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
    <table class="style1">
        <tr>
            <td class="style4">
    <asp:Label ID="Label1" runat="server" Text="Empno"></asp:Label>
            </td>
            <td class="style8">
    <asp:TextBox ID="empno" runat="server" ></asp:TextBox>
            </td>
            <td class="style5" rowspan="8">
                <asp:AccessDataSource ID="AccessDataSource1" runat="server" 
                    DataFile="~/App_Data/Exgratia.accdb" 
        SelectCommand="SELECT * FROM [dependent] WHERE ([empno] = ?)" UpdateCommand="UPDATE [dependent] SET [Title]=@title, [Dep_Name] =@dependent, [Relation]=@relation, [DOB] = @dob, [Vendor_no]=@vendorno, [Death_dt]=@Textboxdeath WHERE [empno] = @empno">
                    <SelectParameters>
                        <asp:SessionParameter   SessionField="user" Name="empno" Type="String" />
                    </SelectParameters>
                </asp:AccessDataSource>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    CellPadding="4" DataSourceID="AccessDataSource1" ForeColor="#333333" 
                    GridLines="None" HorizontalAlign="Center" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"  
                    Height="156px" style="margin-left: 0px" Width="100%" 
                    >
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <Columns>
                        <asp:BoundField DataField="empno" HeaderText="empno" SortExpression="empno"/>
                        <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                        <asp:BoundField DataField="Dep_Name" HeaderText="Dep_Name" 
                            SortExpression="Dep_Name" />
                        <asp:BoundField DataField="Relation" HeaderText="Relation" 
                            SortExpression="Relation" />
                        <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                        <asp:BoundField DataField="Vendor_no" HeaderText="Vendor_no" 
                            SortExpression="Vendor_no" />
                        <asp:BoundField DataField="Death_dt" HeaderText="Death_dt" 
                            SortExpression="Death_dt" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="#506C8C" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                </asp:GridView>
            </td>
            <td class="style5">
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3">
    <asp:Label ID="Label2" runat="server" Text="Title"></asp:Label>
            </td>
            <td class="style8">
    <asp:TextBox ID="title" runat="server"></asp:TextBox>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3">
    <asp:Label ID="Label3" runat="server" Text="Name of dependent"></asp:Label>
            </td>
            <td class="style8">
    <asp:TextBox ID="dependent" runat="server"></asp:TextBox>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3">
                <asp:Label ID="Label5" runat="server" Text="Relation"></asp:Label>
            </td>
            <td class="style8">
                <asp:DropDownList ID="relation" runat="server" DataSourceID="AccessDataSource2" 
                    DataTextField="relation" DataValueField="relation" >
                </asp:DropDownList>
                <asp:AccessDataSource ID="AccessDataSource2" runat="server" 
                    DataFile="~/App_Data/Exgratia.accdb" SelectCommand="SELECT * FROM [Relation]">
                </asp:AccessDataSource>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style6">
                <asp:Label ID="Label7" runat="server" Text="DOB"></asp:Label>
            </td>
            <td class="style9">
                <asp:TextBox ID="dob" runat="server"></asp:TextBox>
                
                <rjs:PopCalendar ID="PopCalendar1" runat="server" Control="dob" />
                
                <asp:Label ID="Label8" runat="server" Text="{mm/dd/yyyy}"></asp:Label>
                
            </td>
            <td class="style7">
                &nbsp;</td>
        </tr >
        <tr>
            <td class="style3">
                <asp:Label ID="Label6" runat="server" Text="Vendor no"></asp:Label>
            </td>
            <td class="style8">
                <asp:TextBox ID="vendorno" runat="server"></asp:TextBox>
                  <asp:CompareValidator ID="CompareValidator1" runat="server" Operator="DataTypeCheck" Type="Integer" 
 ControlToValidate="vendorno" ErrorMessage="Value must be a whole number" />
              
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3">
                <asp:Label ID="labeldeath" runat="server" Text="Death date"></asp:Label>
            </td>
            <td class="style8">
                <asp:TextBox ID="Textboxdeath" runat="server"></asp:TextBox>
                <rjs:PopCalendar ID="PopCalendar2" runat="server" Control="Textboxdeath" />
                <asp:Label ID="Label9" runat="server" Text="{mm/dd/yyyy}"></asp:Label>
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td align="right" class="style2" colspan="2">
                <br />
                <br />
                <br />
                <br />
                <asp:Button ID="insert" runat="server" onclick="Button1_Click1" 
                    Text="Add Dependent" Height="30px" style="margin-right: 0px" />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                &nbsp;
    <asp:Button ID="cancel" runat="server" Text="Cancel" 
    onclick="Button1_Click" CausesValidation="False" style="margin-right: 5px" Width="91px" 
                    Height="30px" />
    &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;
            &nbsp;&nbsp;
                </td>
            <td align="right" class="style2">
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style2">
                &nbsp;</td>
            <td class="style8">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label_err" runat="server" Text=""></asp:Label>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
                <asp:Label ID="Labelresult" runat="server" Text="" 
        style="font-weight: 700"></asp:Label>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
                <br />
    <br />
                <br />
    <br />
<br />
</asp:Content>

